/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.30
 * Generated at: 2020-05-13 18:00:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class corona_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/json; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("[\r\n");
      out.write("   {\r\n");
      out.write("      \"id\":\"1\",\r\n");
      out.write("      \"name\":\"환자1\",\r\n");
      out.write("      \"sex\":\"Female\",\r\n");
      out.write("      \"age\":\"35\",\r\n");
      out.write("      \"nationality\":\"CHN\",\r\n");
      out.write("      \"meet\":\"45\",\r\n");
      out.write("      \"risk\":\"4\",\r\n");
      out.write("      \"img\":\"img01.png\",\r\n");
      out.write("      \"location\":[\r\n");
      out.write("         {\r\n");
      out.write("          \"no\":\"1\",\"name\":\"인천광역시\",\"lat\":\"37.4785301\",\"lon\":\"126.6663099\"\r\n");
      out.write("       }]\r\n");
      out.write("   },\r\n");
      out.write("   {\r\n");
      out.write("      \"id\":\"2\",\r\n");
      out.write("      \"name\":\"환자2\",\r\n");
      out.write("      \"sex\":\"Male\",\r\n");
      out.write("      \"age\":\"55\",\r\n");
      out.write("      \"nationality\":\"KOR\",\r\n");
      out.write("      \"meet\":\"75\",\r\n");
      out.write("      \"risk\":\"3.5\",\r\n");
      out.write("      \"img\":\"img02.png\",\r\n");
      out.write("      \"location\":[\r\n");
      out.write("        {\"no\" : \"1\" , \"name\" : \"김포공항 \" , \"lat\" : \"37.5607255 \" , \"lon\" : \"126.7570715\"},\r\n");
      out.write("        {\"no\" : \"2\" , \"name\" : \"국립중앙 \" , \"lat\" : \"37.5672454\" , \"lon\" : \"127.0034649\"}\r\n");
      out.write("     ]\r\n");
      out.write("   },\r\n");
      out.write("   {\r\n");
      out.write("      \"id\":\"3\",\r\n");
      out.write("      \"name\":\"환자3\",\r\n");
      out.write("      \"sex\":\"Male\",\r\n");
      out.write("      \"age\":\"54\",\r\n");
      out.write("      \"nationality\":\"KOR\",\r\n");
      out.write("      \"meet\":\"98\",\r\n");
      out.write("      \"risk\":\"2\",\r\n");
      out.write("      \"img\":\"img03.png\",\r\n");
      out.write("      \"location\":[\r\n");
      out.write("       {\"no\" : \"1\" , \"name\" : \"인천공항\" , \"lat\" : \"37.4961583\" , \"lon\" : \"126.4529142\"},\r\n");
      out.write("       {\"no\" : \"2\" , \"name\" : \"강남일대 성형외과\" , \"lat\" : \"37.525714\" , \"lon\" : \"127.027734\"},\r\n");
      out.write("       {\"no\" : \"3\" , \"name\" : \"강남구 호텔 투숙\" , \"lat\" : \"37.503774\" , \"lon\" : \"127.049174\"},\r\n");
      out.write("       {\"no\" : \"3\" , \"name\" : \"한강 산책\" , \"lat\" : \"37.525066\" , \"lon\" : \"127.016248\"},\r\n");
      out.write("       {\"no\" : \"4\" , \"name\" : \"강남구 일대 음식점\" , \"lat\" : \"37.529349\" , \"lon\" : \"127.032647\"},\r\n");
      out.write("       {\"no\" : \"5\" , \"name\" : \"일산역 음식점 카페 \" , \"lat\" : \"37.681997\" , \"lon\" : \"126.7678513\"},\r\n");
      out.write("       {\"no\" : \"6\" , \"name\" : \"명지병원\" , \"lat\" : \"37.642134\" , \"lon\" : \"126.8312317\"}\r\n");
      out.write("    ]\r\n");
      out.write("   },\r\n");
      out.write("   {\r\n");
      out.write("      \"id\":\"4\",\r\n");
      out.write("      \"name\":\"환자4\",\r\n");
      out.write("      \"sex\":\"Male\",\r\n");
      out.write("      \"age\":\"55\",\r\n");
      out.write("      \"nationality\":\"KOR\",\r\n");
      out.write("      \"meet\":\"172\",\r\n");
      out.write("      \"risk\":\"5\",\r\n");
      out.write("      \"img\":\"img04.png\",\r\n");
      out.write("      \"location\":[\r\n");
      out.write("         {\"no\" : \"1\" , \"name\" : \"인천 국제 공항\" , \"lat\" : \"37.4961583 \" , \"lon\" : \"126.4529142\"},\r\n");
      out.write("         {\"no\" : \"2\" , \"name\" : \"평택 송탄 터미널\" , \"lat\" : \"37.0796065\" , \"lon\" : \"127.058293\"},\r\n");
      out.write("         {\"no\" : \"3\" , \"name\" : \"평택365연합의원\" , \"lat\" : \"37.0520115\" , \"lon\" : \"127.0573201\"},\r\n");
      out.write("         {\"no\" : \"4\" , \"name\" : \"분당 서울대 병원\" , \"lat\" : \"37.3513241\" , \"lon\" : \"127.123432\"}\r\n");
      out.write("      ]\r\n");
      out.write("   },\r\n");
      out.write("   {\r\n");
      out.write("      \"id\":\"5\",\r\n");
      out.write("      \"name\":\"환자5\",\r\n");
      out.write("      \"sex\":\"Male\",\r\n");
      out.write("      \"age\":\"33\",\r\n");
      out.write("      \"nationality\":\"KOR\",\r\n");
      out.write("      \"meet\":\"29\",\r\n");
      out.write("      \"risk\":\"2\",\r\n");
      out.write("      \"img\":\"img05.png\",\r\n");
      out.write("      \"location\":[\r\n");
      out.write("         {\r\n");
      out.write("            \"no\":\"1\",\r\n");
      out.write("            \"name\":\"성신여대입구\",\r\n");
      out.write("            \"lat\":\"37.5925601\",\r\n");
      out.write("            \"lon\":\"127.0170483\"\r\n");
      out.write("         },\r\n");
      out.write("         {\r\n");
      out.write("            \"no\":\"2\",\r\n");
      out.write("            \"name\":\"중랑구 보건소\",\r\n");
      out.write("            \"lat\":\"37.6064978\",\r\n");
      out.write("            \"lon\":\"127.0927615\"\r\n");
      out.write("         },\r\n");
      out.write("         {\r\n");
      out.write("            \"no\":\"3\",\r\n");
      out.write("            \"name\":\"서울 의료원\",\r\n");
      out.write("            \"lat\":\"37.6122615\",\r\n");
      out.write("            \"lon\":\"127.0973862\"\r\n");
      out.write("         },                      \r\n");
      out.write("         {\r\n");
      out.write("            \"no\":\"4\",\r\n");
      out.write("            \"name\":\"인천공항\",\r\n");
      out.write("            \"lat\":\"37.4601908\",\r\n");
      out.write("            \"lon\":\"126.4231862\"\r\n");
      out.write("         }\r\n");
      out.write("      ]\r\n");
      out.write("   },\r\n");
      out.write("   {\r\n");
      out.write("      \"id\":\"6\",\r\n");
      out.write("      \"name\":\"환자6\",\r\n");
      out.write("      \"sex\":\"Male\",\r\n");
      out.write("      \"age\":\"55\",\r\n");
      out.write("      \"nationality\":\"KOR\",\r\n");
      out.write("      \"meet\":\"25\",\r\n");
      out.write("      \"risk\":\"3.5\",\r\n");
      out.write("      \"img\":\"img06.png\",\r\n");
      out.write("      \"location\":[\r\n");
      out.write("         {\r\n");
      out.write("            \"no\":\"1\",\r\n");
      out.write("            \"name\":\"맑은물 가온교회\",\r\n");
      out.write("            \"lat\":\"37.5877553\",\r\n");
      out.write("            \"lon\":\"126.9999519\"\r\n");
      out.write("         },\r\n");
      out.write("         {\r\n");
      out.write("            \"no\":\"2\",\r\n");
      out.write("            \"name\":\"서울대학병원\",\r\n");
      out.write("            \"lat\":\"37.5787082\",\r\n");
      out.write("            \"lon\":\"126.9975506\"\r\n");
      out.write("         }\r\n");
      out.write("      ]\r\n");
      out.write("   },\r\n");
      out.write("   {\r\n");
      out.write("      \"id\":\"7\",\r\n");
      out.write("      \"name\":\"환자7\",\r\n");
      out.write("      \"sex\":\"Male\",\r\n");
      out.write("      \"age\":\"28\",\r\n");
      out.write("      \"nationality\":\"KOR\",\r\n");
      out.write("      \"meet\":\"21\",\r\n");
      out.write("      \"risk\":\"3.5\",\r\n");
      out.write("      \"img\":\"img07.png\",\r\n");
      out.write("      \"location\":[\r\n");
      out.write("         {\"no\" : \"1\" , \"name\" : \"국제 공항\" , \"lat\" : \"37.4961583\" , \"lon\" : \"126.4529142 \"},\r\n");
      out.write("         {\"no\" : \"2\" , \"name\" : \"서울 의료원\" , \"lat\" : \"37.6127653\" , \"lon\" : \"127.097785\"}\r\n");
      out.write("      ]\r\n");
      out.write("   },\r\n");
      out.write("   {\r\n");
      out.write("      \"id\":\"8\",\r\n");
      out.write("      \"name\":\"환자8\",\r\n");
      out.write("      \"sex\":\"Female\",\r\n");
      out.write("      \"age\":\"62\",\r\n");
      out.write("      \"nationality\":\"KOR\",\r\n");
      out.write("      \"meet\":\"76\",\r\n");
      out.write("      \"risk\":\"4\",\r\n");
      out.write("      \"img\":\"img08.png\",\r\n");
      out.write("      \"location\":[\r\n");
      out.write("         {\"no\" : \"1\" , \"name\" : \"국제 공항 \" , \"lat\" : \"37.4961583\" , \"lon\" : \"126.4529142 \"},\r\n");
      out.write("         {\"no\" : \"2\" , \"name\" : \"서초동 소재 음식점\" , \"lat\" : \"37.491124\" , \"lon\" : \"127.011744\"},\r\n");
      out.write("         {\"no\" : \"3\" , \"name\" : \"대중 목욕탕 방문 음시점 \" , \"lat\" : \"35.986943\" , \"lon\" : \"126.70818\"},\r\n");
      out.write("         {\"no\" : \"4\" , \"name\" : \"군산 소재 의료가관\" , \"lat\" : \"35.967793\" , \"lon\" : \"126.716062\"},\r\n");
      out.write("         {\"no\" : \"5\" , \"name\" : \"전라북도 군산의료원\" , \"lat\" : \"35.954685\" , \"lon\" : \"126.7124545\"},\r\n");
      out.write("         {\"no\" : \"6\" , \"name\" : \"원광대병원\" , \"lat\" : \"35.9647171\" , \"lon\" : \"126.9568068\"}\r\n");
      out.write("      ]\r\n");
      out.write("   },\r\n");
      out.write("   {\r\n");
      out.write("      \"id\":\"9\",\r\n");
      out.write("      \"name\":\"환자9\",\r\n");
      out.write("      \"sex\":\"Female\",\r\n");
      out.write("      \"age\":\"28\",\r\n");
      out.write("      \"nationality\":\"KOR\",\r\n");
      out.write("      \"meet\":\"25\",\r\n");
      out.write("      \"risk\":\"3.5\",\r\n");
      out.write("      \"img\":\"img09.png\",\r\n");
      out.write("      \"location\":[\r\n");
      out.write("         {\"no\":\"1\",\"name\":\"서울의료원\",\"lat\":\"37.6127653\",\"lon\":\"127.097785\"}\r\n");
      out.write("      ]\r\n");
      out.write("   },\r\n");
      out.write("   {\r\n");
      out.write("      \"id\":\"10\",\r\n");
      out.write("      \"name\":\"환자10\",\r\n");
      out.write("      \"sex\":\"Female\",\r\n");
      out.write("      \"age\":\"54\",\r\n");
      out.write("      \"nationality\":\"KOR\",\r\n");
      out.write("      \"meet\":\"1\",\r\n");
      out.write("      \"risk\":\"2\",\r\n");
      out.write("      \"img\":\"img10.png\",\r\n");
      out.write("      \"location\":[\r\n");
      out.write("         {\"no\" : \"1\" , \"name\" : \"고양시 소재 미용실\" , \"lat\" : \"37.640890\" , \"lon\" : \"126.792131\"},\r\n");
      out.write("         {\"no\" : \"2\" , \"name\" : \"서울대병원\" , \"lat\" : \"37.5809111\" , \"lon\" : \"126.9947373\"}\r\n");
      out.write("      ]\r\n");
      out.write("   },\r\n");
      out.write("   {\r\n");
      out.write("      \"id\":\"11\",\r\n");
      out.write("      \"name\":\"환자11\",\r\n");
      out.write("      \"sex\":\"Male\",\r\n");
      out.write("      \"age\":\"25\",\r\n");
      out.write("      \"nationality\":\"KOR\",\r\n");
      out.write("      \"meet\":\"1\",\r\n");
      out.write("      \"risk\":\"2\",\r\n");
      out.write("      \"img\":\"img11.png\",\r\n");
      out.write("      \"location\":[\r\n");
      out.write("         {\"no\" : \"1\" , \"name\" : \"고양시 소재 미용실\" , \"lat\" : \"37.640890\" , \"lon\" : \"126.792131\"},\r\n");
      out.write("         {\"no\" : \"2\" , \"name\" : \"서울대병원\" , \"lat\" : \"37.5809111\" , \"lon\" : \"126.9947373\"}\r\n");
      out.write("      ]\r\n");
      out.write("   },\r\n");
      out.write("   {\r\n");
      out.write("      \"id\":\"12\",\r\n");
      out.write("      \"name\":\"환자12\",\r\n");
      out.write("      \"sex\":\"Male\",\r\n");
      out.write("      \"age\":\"48\",\r\n");
      out.write("      \"nationality\":\"CHN\",\r\n");
      out.write("      \"meet\":\"666\",\r\n");
      out.write("      \"risk\":\"5\",\r\n");
      out.write("      \"img\":\"img11.png\",\r\n");
      out.write("      \"location\":[\r\n");
      out.write("         {\"no\" : \"1\" , \"name\" : \"김포공항\" , \"lat\" : \"37.5599416\" , \"lon\" : \"126.7854458\"},\r\n");
      out.write("         {\"no\" : \"2\" , \"name\" : \"부천 CGV \" , \"lat\" : \"37.5600899\" , \"lon\" : \"126.7330442\"},\r\n");
      out.write("         {\"no\" : \"3\" , \"name\" : \"인천충립국 관리사무소\" , \"lat\" : \"37.461777\" , \"lon\" : \"126.6294428\"},\r\n");
      out.write("         {\"no\" : \"4\" , \"name\" : \"부천 보건소\" , \"lat\" : \"37.5041653\" , \"lon\" : \"126.7729249\"},\r\n");
      out.write("         {\"no\" : \"5\" , \"name\" : \"순천향대학교 부속 부천 병원방문\" , \"lat\" : \"37.1531896\" , \"lon\" : \"126.6701104\"},\r\n");
      out.write("         {\"no\" : \"6\" , \"name\" : \"군포 소재 의료기관\" , \"lat\" : \"37.359258\" , \"lon\" : \"126.930912\"},\r\n");
      out.write("         {\"no\" : \"7\" , \"name\" : \"친척집 방문 \" , \"lat\" : \"37.283094\" , \"lon\" : \"127.019955\"},\r\n");
      out.write("         {\"no\" : \"8\" , \"name\" : \"수원역\" , \"lat\" : \"37.266444\" , \"lon\" : \"126.9972244\"},\r\n");
      out.write("         {\"no\" : \"9\" , \"name\" : \"부천 보건소 재방문\" , \"lat\" : \"37.5041653\" , \"lon\" : \"126.7729249\"},\r\n");
      out.write("         {\"no\" : \"10\" , \"name\" : \"강릉 터미널\" , \"lat\" : \"37.8198838\" , \"lon\" : \"128.8191288\"},\r\n");
      out.write("         {\"no\" : \"11\" , \"name\" : \"서울역\" , \"lat\" : \"37.555197\" , \"lon\" : \"126.97137\"},\r\n");
      out.write("         {\"no\" : \"12\" , \"name\" : \"서울대 병원\" , \"lat\" : \"37.5787082\" , \"lon\" : \"126.9953619\"}\r\n");
      out.write("      ]\r\n");
      out.write("   },\r\n");
      out.write("   {\r\n");
      out.write("      \"id\":\"13\",\r\n");
      out.write("      \"name\":\"환자13\",\r\n");
      out.write("      \"sex\":\"Male\",\r\n");
      out.write("      \"age\":\"28\",\r\n");
      out.write("      \"nationality\":\"KOR\",\r\n");
      out.write("      \"meet\":\"0\",\r\n");
      out.write("      \"risk\":\"1\",\r\n");
      out.write("      \"img\":\"img11.png\",\r\n");
      out.write("      \"location\":[\r\n");
      out.write("         {\"no\" : \"1\" , \"name\" : \"국립중앙의료원\" , \"lat\" : \"37.5672412\" , \"lon\" : \"127.0056589\"}\r\n");
      out.write("      ]\r\n");
      out.write("   },\r\n");
      out.write("   {\r\n");
      out.write("      \"id\":\"14\",\r\n");
      out.write("      \"name\":\"환자14\",\r\n");
      out.write("      \"sex\":\"Female\",\r\n");
      out.write("      \"age\":\"40\",\r\n");
      out.write("      \"nationality\":\"CHN\",\r\n");
      out.write("      \"meet\":\"0\",\r\n");
      out.write("      \"risk\":\"3.5\",\r\n");
      out.write("      \"img\":\"img11.png\",\r\n");
      out.write("      \"location\":[\r\n");
      out.write("         {\"no\" : \"1\" , \"name\" : \"분당 서울대 병원\" , \"lat\" : \"37.3513241 \" , \"lon\" : \"127.123432\"}\r\n");
      out.write("      ]\r\n");
      out.write("   },\r\n");
      out.write("   {\r\n");
      out.write("      \"id\":\"15\",\r\n");
      out.write("      \"name\":\"환자15\",\r\n");
      out.write("      \"sex\":\"Male\",\r\n");
      out.write("      \"age\":\"43\",\r\n");
      out.write("      \"nationality\":\"KOR\",\r\n");
      out.write("      \"meet\":\"14\",\r\n");
      out.write("      \"risk\":\"3.5\",\r\n");
      out.write("      \"img\":\"img11.png\",\r\n");
      out.write("      \"location\":[\r\n");
      out.write("         {\"no\" : \"1\" , \"name\" : \"자택 자가 격리\" , \"lat\" : \"37.297634\" , \"lon\" : \"126.978065\"},\r\n");
      out.write("         {\"no\" : \"2\" , \"name\" : \"장안구 보건소\" , \"lat\" : \"37.3043448\" , \"lon\" : \"127.0101768\"},\r\n");
      out.write("         {\"no\" : \"3\" , \"name\" : \"국군수도 병원\" , \"lat\" : \"37.3928031\" , \"lon\" : \"127.1468967\"}\r\n");
      out.write("      ]\r\n");
      out.write("   },\r\n");
      out.write("   {\r\n");
      out.write("      \"id\":\"16\",\r\n");
      out.write("      \"name\":\"환자16\",\r\n");
      out.write("      \"sex\":\"Female\",\r\n");
      out.write("      \"age\":\"42\",\r\n");
      out.write("      \"nationality\":\"KOR\",\r\n");
      out.write("      \"meet\":\"25\",\r\n");
      out.write("      \"risk\":\"3.5\",\r\n");
      out.write("      \"img\":\"img11.png\",\r\n");
      out.write("      \"location\":[\r\n");
      out.write("         {\"no\" : \"1\" , \"name\" : \"무안 국제 공항\" , \"lat\" : \"34.9935865\" , \"lon\" : \"126.3856506 \"},\r\n");
      out.write("         {\"no\" : \"2\" , \"name\" : \"21세기 병원 진료\" , \"lat\" : \"35.1757929\" , \"lon\" : \"126.8181317\"},\r\n");
      out.write("         {\"no\" : \"3\" , \"name\" : \"전남대 병원\" , \"lat\" : \"35.1007301\" , \"lon\" : \"126.891936\"}\r\n");
      out.write("      ]\r\n");
      out.write("   },\r\n");
      out.write("   {\r\n");
      out.write("      \"id\":\"17\",\r\n");
      out.write("      \"name\":\"환자17\",\r\n");
      out.write("      \"sex\":\"Male\",\r\n");
      out.write("      \"age\":\"38\",\r\n");
      out.write("      \"nationality\":\"KOR\",\r\n");
      out.write("      \"meet\":\"1\",\r\n");
      out.write("      \"risk\":\"3.5\",\r\n");
      out.write("      \"img\":\"img11.png\",\r\n");
      out.write("      \"location\":[\r\n");
      out.write("         {\"no\" : \"1\" , \"name\" : \"명지병원\" , \"lat\" : \"37.642134\" , \"lon\" : \"126.8312317\"}\r\n");
      out.write("      ]\r\n");
      out.write("   },\r\n");
      out.write("   {\r\n");
      out.write("      \"id\":\"18\",\r\n");
      out.write("      \"name\":\"환자18\",\r\n");
      out.write("      \"sex\":\"Female\",\r\n");
      out.write("      \"age\":\"21\",\r\n");
      out.write("      \"nationality\":\"KOR\",\r\n");
      out.write("      \"meet\":\"1\",\r\n");
      out.write("      \"risk\":\"3.5\",\r\n");
      out.write("      \"img\":\"img11.png\",\r\n");
      out.write("      \"location\":[\r\n");
      out.write("         {\"no\" : \"1\" , \"name\" : \"전남대 병원\" , \"lat\" : \"35.1007301\" , \"lon\" : \"126.891936\"}\r\n");
      out.write("      ]\r\n");
      out.write("   }, \r\n");
      out.write("   {\r\n");
      out.write("      \"id\":\"19\",\r\n");
      out.write("      \"name\":\"중국관광객\",\r\n");
      out.write("      \"sex\":\"Female\",\r\n");
      out.write("      \"age\":\"55\",\r\n");
      out.write("      \"nationality\":\"CHN\",\r\n");
      out.write("      \"meet\":\"25\",\r\n");
      out.write("      \"risk\":\"5\",\r\n");
      out.write("      \"img\":\"img11.png\",\r\n");
      out.write("      \"location\":[\r\n");
      out.write("         {\"no\" : \"1\" , \"name\" : \"도두해안도로\" , \"lat\" : \"33.5053682\" , \"lon\" : \"126.4672262\"},\r\n");
      out.write("         {\"no\" : \"2\" , \"name\" : \"누웨마루거리\" , \"lat\" : \"33.4872178\" , \"lon\" : \"126.4915267\"},\r\n");
      out.write("         {\"no\" : \"3\" , \"name\" : \"신라 면세점\" , \"lat\" : \"33.4860719\" , \"lon\" : \"126.4853878\"},\r\n");
      out.write("         {\"no\" : \"4\" , \"name\" : \"제주시 호텔\", \"lat\" : \"33.486278\" , \"lon\" : \"126.485350\"},\r\n");
      out.write("         {\"no\" : \"5\" , \"name\" : \"제주공항 \" , \"lat\" : \"33.5104135\" , \"lon\" : \"126.4891647\"},\r\n");
      out.write("         {\"no\" : \"6\" , \"name\" : \"칠성동에서 이동\" , \"lat\" : \"33.5142011\" , \"lon\" : \"126.5250222\"},\r\n");
      out.write("         {\"no\" : \"7\" , \"name\" : \"1100고지\" , \"lat\" : \"33.3576061\" , \"lon\" : \"126.4606808\"},\r\n");
      out.write("         {\"no\" : \"8\" , \"name\" : \"에코렌드\" , \"lat\" : \"33.4470415\" , \"lon\" : \"126.6652565\"},\r\n");
      out.write("         {\"no\" : \"9\" , \"name\" : \"산굼부리\" , \"lat\" : \"33.4316252\" , \"lon\" : \"126.6878225\"},\r\n");
      out.write("         {\"no\" : \"10\" , \"name\" : \"우도 \" , \"lat\" : \"33.5043639\" , \"lon\" : \"126.9191144\"},\r\n");
      out.write("         {\"no\" : \"11\" , \"name\" : \"일출봉 \" , \"lat\" : \"33.4581222\" , \"lon\" : \"126.9075664\"}\r\n");
      out.write("      ]\r\n");
      out.write("   },\r\n");
      out.write("\t{\r\n");
      out.write("\t      \"id\":\"20\",\r\n");
      out.write("\t      \"name\":\"환자20\",\r\n");
      out.write("\t      \"sex\":\"Female\",\r\n");
      out.write("\t      \"age\":\"41\",\r\n");
      out.write("\t      \"nationality\":\"KOR\",\r\n");
      out.write("\t      \"meet\":\"1\",\r\n");
      out.write("\t      \"risk\":\"4\",\r\n");
      out.write("\t      \"img\":\"img11.png\",\r\n");
      out.write("\t      \"location\":[\r\n");
      out.write("\t{\"no\" : \"1\" , \"name\" : \"수원 천천동\" , \"lat\" : \"37.2958286 \" , \"lon\" : \"126.9692372 \"},\r\n");
      out.write("\t{\"no\" : \"2\" , \"name\" : \"영등포\" , \"lat\" : \"37.5154133 \" , \"lon\" : \"126.9049401 \"},\r\n");
      out.write("\t{\"no\" : \"3\" , \"name\" : \"국군수도 병원\" , \"lat\" : \"37.3928031\" , \"lon\" : \"127.1468967\"}\r\n");
      out.write("\t]\r\n");
      out.write("\t},\r\n");
      out.write("\t{\r\n");
      out.write("\t      \"id\":\"21\",\r\n");
      out.write("\t      \"name\":\"환자21\",\r\n");
      out.write("\t      \"sex\":\"Female\",\r\n");
      out.write("\t      \"age\":\"59\",\r\n");
      out.write("\t      \"nationality\":\"KOR\",\r\n");
      out.write("\t      \"meet\":\"1\",\r\n");
      out.write("\t      \"risk\":\"2\",\r\n");
      out.write("\t      \"img\":\"img11.png\",\r\n");
      out.write("\t      \"location\":[      \r\n");
      out.write("\t{\"no\" : \"1\" , \"name\" : \"종로구 명륜교회\" , \"lat\" : \"37.5870685 \" , \"lon\" : \"126.9921603\"},\r\n");
      out.write("\t{\"no\" : \"2\" , \"name\" : \"성북구 보건소\" , \"lat\" : \"37.6026426 \" , \"lon\" : \"127.0373294\"},\r\n");
      out.write("\t{\"no\" : \"3\" , \"name\" : \"서울대 병원\" , \"lat\" : \"37.579392 \" , \"lon\" : \"126.9971943\"}\r\n");
      out.write("\t]\r\n");
      out.write("\t},\r\n");
      out.write("\t{\r\n");
      out.write("\t      \"id\":\"22\",\r\n");
      out.write("\t      \"name\":\"환자22\",\r\n");
      out.write("\t      \"sex\":\"Male\",\r\n");
      out.write("\t      \"age\":\"46\",\r\n");
      out.write("\t      \"nationality\":\"KOR\",\r\n");
      out.write("\t      \"meet\":\"1\",\r\n");
      out.write("\t      \"risk\":\"3\",\r\n");
      out.write("\t      \"img\":\"img11.png\",\r\n");
      out.write("\t      \"location\":[         \r\n");
      out.write("\t{\"no\" : \"1\" , \"name\" : \"나주 시청\" , \"lat\" : \"35.015893 \" , \"lon\" : \"126.7086793\"},\r\n");
      out.write("\t{\"no\" : \"2\" , \"name\" : \"조선대병원\" , \"lat\" : \"35.1386047 \" , \"lon\" : \"126.9244892\"}\r\n");
      out.write("\t]\r\n");
      out.write("\t},\r\n");
      out.write("\t{\r\n");
      out.write("\t      \"id\":\"23\",\r\n");
      out.write("\t      \"name\":\"환자23\",\r\n");
      out.write("\t      \"sex\":\"Female\",\r\n");
      out.write("\t      \"age\":\"58\",\r\n");
      out.write("\t      \"nationality\":\"CHN\",\r\n");
      out.write("\t      \"meet\":\"54\",\r\n");
      out.write("\t      \"risk\":\"5\",\r\n");
      out.write("\t      \"img\":\"img11.png\",\r\n");
      out.write("\t      \"location\":[        \r\n");
      out.write("\t{\"no\" : \"1\" , \"name\" : \"인천공항\" , \"lat\" : \"37.4961583\" , \"lon\" : \"126.4529142\"},\r\n");
      out.write("\t{\"no\" : \"2\" , \"name\" : \"프레지던트 \" , \"lat\" : \"37.565622 \" , \"lon\" : \"126.9772543\"},\r\n");
      out.write("\t{\"no\" : \"3\" , \"name\" : \"롯데백화점 \" , \"lat\" : \"37.5642783 \" , \"lon\" : \"126.9735954\"},\r\n");
      out.write("\t{\"no\" : \"4\" , \"name\" : \"이마트 \" , \"lat\" : \"37.542371 \" , \"lon\" : \"126.9511733\"},\r\n");
      out.write("\t{\"no\" : \"5\" , \"name\" : \"프레지던트호텔 \" , \"lat\" : \"37.565622 \" , \"lon\" : \"126.9772543\"},\r\n");
      out.write("\t{\"no\" : \"6\" , \"name\" : \"서대문구 보건소\" , \"lat\" : \"37.5740481 \" , \"lon\" : \"126.9312611\"},\r\n");
      out.write("\t{\"no\" : \"7\" , \"name\" : \"국립중앙의료원\" , \"lat\" : \"37.5672412\" , \"lon\" : \"127.0056589\"}\r\n");
      out.write("\t]\r\n");
      out.write("\t},\r\n");
      out.write("\t{\r\n");
      out.write("\t      \"id\":\"24\",\r\n");
      out.write("\t      \"name\":\"환자24\",\r\n");
      out.write("\t      \"sex\":\"Male\",\r\n");
      out.write("\t      \"age\":\"28\",\r\n");
      out.write("\t      \"nationality\":\"KOR\",\r\n");
      out.write("\t      \"meet\":\"300\",\r\n");
      out.write("\t      \"risk\":\"5\",\r\n");
      out.write("\t      \"img\":\"img11.png\",\r\n");
      out.write("\t      \"location\":[\r\n");
      out.write("\t{\"no\" : \"1\" , \"name\" : \"김포공항 \" , \"lat\" : \"37.5599086\" , \"lon\" : \"126.7941577\"},\r\n");
      out.write("\t{\"no\" : \"2\" , \"name\" : \"아산 임시 생활시설\" , \"lat\" : \"36.6584564\" , \"lon\" : \"126.6688899\"},\r\n");
      out.write("\t{\"no\" : \"3\" , \"name\" : \"국립중앙의료원\" , \"lat\" : \"37.5672412\" , \"lon\" : \"127.0056589\"}\r\n");
      out.write("\t]\r\n");
      out.write("\t},\r\n");
      out.write("{\r\n");
      out.write("\t      \"id\":\"25\",\r\n");
      out.write("\t      \"name\":\"환자25\",\r\n");
      out.write("\t      \"sex\":\"Fale\",\r\n");
      out.write("\t      \"age\":\"28\",\r\n");
      out.write("\t      \"nationality\":\"KOR\",\r\n");
      out.write("\t      \"meet\":\"300\",\r\n");
      out.write("\t      \"risk\":\"5\",\r\n");
      out.write("\t      \"img\":\"img11.png\",\r\n");
      out.write("\t      \"location\":[\r\n");
      out.write("\t{\"no\" : \"1\" , \"name\" : \"안양동 490-19 \" , \"lat\" : \"37.3881737\" , \"lon\" : \"126.928744\"}\r\n");
      out.write("\t]\r\n");
      out.write("\t}\t\r\n");
      out.write("]");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
